[phases.setup]
# Usar JDK 21 no setup (build)
nixPkgs = ["jdk21"]

[phases.build]
# Comando para build do uberjar Clojure com Leiningen
command = "lein uberjar"

[phases.start]
# Comando para rodar a aplicação
command = "java -jar target/uberjar/feedback-api-standalone.jar"

[options]
# Definir diretório da aplicação (opcional, se a raiz do projeto for /app)
appLocation = "/app"
